version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install
      - cd android
      - ls
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace
artifacts:
  files:
    -app/build/outputs/apk/the-job-portal-app.apk
