# version: 0.2
# phases:
#   install:
#     runtime-versions:
#         nodejs: 10
#     commands:
#       - echo Nothing to do in the install phase...
#       - npm install 
#   pre_build:
#     commands:
#       - android-accept-licenses.sh "android update sdk --no-ui --all --use-sdk-wrapper --filter \"android-$ANDROID_VERSION,tools,platform-tools,build-tools-$ANDROID_TOOLS_VERSION,extra-android-m2repository\""
#       - echo "y" | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
#   build:
#     commands:
#       - cd android
#       - chmod +x gradlew
#       - ./gradlew build
# artifacts:
#   files:
#     - app/build/outputs/apk/the-job-portal-debug.apk
#   discard-paths: yes



# version: 0.2

# phases:
#   install:
#     runtime-versions:
#         nodejs: 10
#     commands:
#       - echo Nothing to do in the install phase...
#       - npm install
#   pre_build:
#     commands:
#       - echo Pre Build started on `date`
#       - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
#       - tar -xvf android-sdk_r24.4.1-linux.tgz
#       - mv android-sdk-linux /opt/
#       - export ANDROID_HOME=/opt/android-sdk-linux
#       - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
#       - export ANDROID_SWT=$ANDROID_HOME/tools/lib/arm
#       - mkdir $ANDROID_HOME/licenses
#       - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
#       - /opt/android-sdk-linux/tools/android update sdk --no-ui
#       - ls
#       - cd android
#       - chmod +x gradlew
#       - ./gradlew assembleDebug --stacktrace
#   build:
#     commands:
#       # - root/./gradlew --debug --stacktrace build
#       # - root/./gradlew assemble
#       # - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3" "platforms;android-27"

#   post_build:
#     commands:
#       - echo Build completed on `date`
# artifacts:
#   files:
#     -app/build/outputs/apk/the-job-portal-app.apk

version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
        android: 29
        java: corretto8
    commands:
      - npm install
      # - ls
      # - cd ..
      # - ls
      # - cd ..
      # - ls
      # - cd ..
      # - ls
      # - cd ..
      # - ls
      # - cd usr/lib
      # - ls
      
  build:
    commands:
      - ls
      # - export ANDROID_HOME=$HOME/Android/Sdk
      # - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
      # - echo $ANDROID_SDK_ROOT
      # - export PATH=$PATH:$ANDROID_HOME/tools
      # - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
      - unzip sdk-tools-linux-4333796.zip -d android-sdk
      - mv android-sdk /opt/
      - export ANDROID_SDK_ROOT=/opt/android-sdk
      - echo "export ANDROID_SDK_ROOT=/opt/android-sdk" >> ~/.bashrc
      - echo "export PATH=$PATH:$ANDROID_SDK_ROOT/tools" >> ~/.bashrc
      - cd android/app
      - keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Mark Smith, OU=Java, O=Oracle, L=Cupertino, S=California, C=US"
      - cd ..
      - ls 
      - chmod +x gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
    - app/build/outputs/app-debug.apk
