version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo Nothing to do in the install phase...
      - sudo apt-get -y install wget
      - npm install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      - tar zxvf android-sdk_r24.4.1-linux.tgz
      - mkdir -p android-sdk-linux/licenses
      - cp android-sdk-license ./android-sdk-linux/licenses/
      - echo sdk.dir='pwd'/android-sdk-linux > local.properties
      - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
      - unzip android-ndk-r13b-linux-x86_64.zip
      - export ANDROID_NDK_HOME=`pwd`/android-ndk-r13b
      - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
      - echo "sdk.dir=$ANDROID_HOME" > local.properties
      - echo "ndk.dir=$ANDROID_NDK_HOME" >> local.properties
  build:
    commands:
      # - root/./gradlew --debug --stacktrace build
      # - root/./gradlew assemble
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    -app/build/outputs/apk/the-job-portal-app.apk
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#         nodejs: 10
#     commands:
#       - npm install
      
#   build:
#     commands:
#       - cd android
#       - ls
#       - export ANDROID_HOME=$HOME/Android/Sdk
#       - echo $ANDROID_SDK_ROOT
#       - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
#       - export PATH=$PATH:$ANDROID_HOME/tools
#       - export PATH=$PATH:$ANDROID_HOME/platform-tools
#       - chmod +x gradlew
#       - ./gradlew assembleDebug --stacktrace
# artifacts:
#   files:
#     -app/build/outputs/apk/the-job-portal-app.apk
