version: 0.2

phases:
  build:
    commands:
      - cd android
      - ls
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace
artifacts:
  files:
    -app/build/outputs/apk/the-job-portal-app.apk
