version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo Nothing to do in the install phase...
      - npm install
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
      # - wget kc://dl.google.com/dl/android/studio/ide-zips/3.4.0.18/android-studio-ide-183.5452501-linux.tar.gz
      - tar -xvf android-sdk_r24.4.1-linux.tgz
      - mv android-sdk-linux /opt/
      - export ANDROID_HOME=/opt/android-sdk-linux
      - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
      - mkdir $ANDROID_HOME/licenses
      - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license
      - /okpt/android-sdk-linux/tools/android update sdk --no-ui
      - ls
      - cd android
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace
  build:
    commands:
      # - root/./gradlew --debug --stacktrace build
      # - root/./gradlew assemble
      # - $ANDROID_HOME/tools/bin/sdkmanager "build-tools;27.0.3" "platforms;android-27"

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    -app/build/outputs/apk/the-job-portal-app.apk
# version: 0.2

# phases:
#   install:
#     runtime-versions:
#         nodejs: 10
#     commands:
#       - npm install

#   build:
#     commands:
#       - cd android
#       - ls
#       - export ANDROID_HOME=$HOME/Android/Sdk
#       - echo $ANDROID_SDK_ROOT
#       - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
#       - export PATH=$PATH:$ANDROID_HOME/tools
#       - export PATH=$PATH:$ANDROID_HOME/platform-tools
#       - chmod +x gradlew
#       - ./gradlew assembleDebug --stacktrace
# artifacts:
#   files:
#     -app/build/outputs/apk/the-job-portal-app.apk
