version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - npm install
      
  build:
    commands:
      - cd android
      - ls
      - export ANDROID_HOME=$HOME/Android/Sdk
      - echo $ANDROID_SDK_ROOT
      - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
      - export PATH=$PATH:$ANDROID_HOME/tools
      - export PATH=$PATH:$ANDROID_HOME/platform-tools
      - chmod +x gradlew
      - ./gradlew assembleDebug --stacktrace
artifacts:
  files:
    -app/build/outputs/apk/the-job-portal-app.apk
